export type PrimaryFormControl = {
  firstName: string;
  lastName: string;
  cpf: string;
  warNameConfirmation: "Sim" | "Não";
  warName?: string | undefined;
  otherNamesConfirmation: "Sim" | "Não";
  sex: "Masculino" | "Feminino";
  maritalStatus: string;
  birthDate: Date;
  birthCity: string;
  birthState: string;
  birthCountry: string;
  originCountry: string;
  otherNationalityConfirmation: "Sim" | "Não";
  otherNationalityPassport?: string | undefined;
  otherCountryResidentConfirmation: "Sim" | "Não";
  USSocialSecurityNumber: string;
  USTaxpayerIDNumber: string;
  address: string;
  city: string;
  state: string;
  cep: string;
  country: string;
  postalAddressConfirmation: "Sim" | "Não";
  otherPostalAddress: string;
  cel: string;
  tel: string;
  fiveYearsOtherTelConfirmation: "Sim" | "Não";
  otherTel: string;
  email: string;
  fiveYearsOtherEmailConfirmation: "Sim" | "Não";
  otherEmail: string;
  facebook: string;
  linkedin: string;
  instagram: string;
  othersSocialMedia: string;
  passportNumber: string;
  passportCity: string;
  passportState: string;
  passportIssuingCountry: string;
  passportIssuingDate: Date;
  passportExpireDate?: Date | undefined;
  passportNoExpireDate: boolean;
  passportLostConfirmation: "Sim" | "Não";
  lostPassportNumber: string;
  lostPassportCountry: string;
  lostPassportDetails: string;
  travelItineraryConfirmation: "Sim" | "Não";
  USAPreviewArriveDate: Date;
  arriveFlyNumber: string;
  arriveCity: string;
  USAPreviewReturnDate: Date;
  returnFlyNumber: string;
  returnCity: string;
  estimatedTimeOnUSA: string;
  USACompleteAddress: string;
  USAZipCode: string;
  USACity: string;
  USAState: string;
  payerNameOrCompany: string;
  payerTel: string;
  payerAddress: string;
  payerRelation: string;
  payerEmail: string;
  otherPeopleTravelingConfirmation: "Sim" | "Não";
  groupMemberConfirmation: "Sim" | "Não";
  groupName: string;
  hasBeenOnUSAConfirmation: "Sim" | "Não";
  americanLicenseToDriveConfirmation: "Sim" | "Não";
  USAVisaConfirmation: "Sim" | "Não";
  visaIssuingDate: Date;
  visaNumber: string;
  newVisaConfirmation: "Sim" | "Não";
  sameCountryResidenceConfirmation: "Sim" | "Não";
  sameVisaTypeConfirmation: "Sim" | "Não";
  fingerprintsProvidedConfirmation: "Sim" | "Não";
  lostVisaConfirmation: "Sim" | "Não";
  lostVisaDetails: string;
  canceledVisaConfirmation: "Sim" | "Não";
  canceledVisaDetails: string;
  deniedVisaConfirmation: "Sim" | "Não";
  deniedVisaDetails: string;
  consularPost: string;
  deniedVisaType: string;
  immigrationRequestByAnotherPersonConfirmation: "Sim" | "Não";
  immigrationRequestByAnotherPersonDetails: string;
};
