import type { Metadata } from "next";
import { Montserrat as FontSans } from "next/font/google";
import { cn } from "@/lib/utils";
import "./globals.css";

const montserrat = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className="min-h-screen" lang="pt-BR">
      <body
        className={cn(
          "relative min-h-screen overflow-x-hidden bg-background font-sans antialiased",
          montserrat.variable,
        )}
      >
        {children}
      </body>
    </html>
  );
}
